name: Generate CN Page

on:
  push:
    branches:
    - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workpath: ./

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ env.workpath }}
    
    - name: Checkout old dist
      uses: actions/checkout@v4
      with:
        ref: 'page'
        path: site

    - name: Remove Site URL
      run: |
        sed -i "/^site_url/d" mkdocs.yml

    - name: Generate page
      run: mkdocs build
      working-directory: ${{ env.workpath }}
      
    - name: Add robots.txt
      working-directory: ${{ env.workpath }}
      run: |
        echo Disallow: / > site/robots.txt

    - name: Push generated page
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        branch: page
        repository: site
        commit_options: '--allow-empty'
        commit_message: |
          update generated page
          Triggered by ${{ github.sha }}
