name: Generate CN Page

on:
  push:
    branches:
    - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workpath: ./

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ env.workpath }}
    
    - name: Checkout old dist
      uses: actions/checkout@v2
      with:
        ref: 'page'
        path: site

    - name: Modify Site URL
      run: |
        sed -i "s/colleges.chat/cn.colleges.chat/g" mkdocs.yml

    - name: Add Cloudflare Web Analytics
      run: |
        sed -i "s/copyright: /copyright: <script defer src='https:\/\/static.cloudflareinsights.com\/beacon.min.js' data-cf-beacon='{\"token\": \"5f330e993b3849818e0e9c10115937bd\"}'><\/script>/g" mkdocs.yml

    - name: Generate page
      run: mkdocs build
      working-directory: ${{ env.workpath }}
      
    - name: Precompress partial files
      working-directory: ${{ env.workpath }}
      run: |
        gzip -k -9 site/*.html
        gzip -r -k -9 site/assets
        gzip -r -k -9 site/choose-a-college
        gzip -r -k -9 site/search

    - name: Push generated page
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: page
        repository: site
        commit_options: '--allow-empty'
        commit_message: |
          update generated page
          Triggered by ${{ github.sha }}
